import type { Metadata } from "next";
import "./globals.css";
import SideBar from "./components/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex items-center justify-center h-screen">
        <div className="container flex rounded-xl p-5 md:w-widthDesk w-4/5 bg-white">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
